/**
 * A note for every move of every lesson, keyed by opening name.
 *
 * The point of a drill is not to memorise a move order but to know why each
 * move is there — so that when the opponent deviates, you still know what you
 * were trying to do. Each note is one sentence about *this* move's purpose.
 *
 * Indexed by ply: [0] is White's first move, [1] Black's reply, and so on.
 */
export const NOTES = {
  "Italian Game": [
    "Takes the centre and opens lines for both the bishop and the queen.",
    "Stakes an equal claim. Black must fight for the centre immediately or be squeezed.",
    "Develops with a threat: the knight attacks e5, so Black must answer.",
    "The natural defender. It guards e5 and develops toward the centre.",
    "The Italian bishop. It stares at f7, the square only the king defends.",
    "The mirror. Black eyes f2 with the same idea.",
    "Quiet but important: it prepares d4 and gives the bishop a retreat square on c2.",
    "Develops and hits e4. Every developing move should carry a threat if it can.",
    "Solid rather than sharp. It supports e4 and opens the c1 bishop.",
    "Black copies: the pawn shields e5 and frees the light-squared bishop.",
    "King to safety, rook toward the centre. Castle before you open the position.",
    "Black completes the same job. The opening is over; now find a plan.",
  ],
  "Ruy Lopez, Morphy Defence": [
    "The king's pawn opening, the most direct fight for the centre.",
    "Black meets it head on.",
    "Attacks e5 and develops. Knights before bishops, as a rule.",
    "Defends the pawn and develops.",
    "The Ruy Lopez. The bishop pressures the knight that is holding e5 up.",
    "The Morphy Defence. It asks the bishop a question before anything else is fixed.",
    "Retreating keeps the bishop on the a2-g8 diagonal, still aiming at the king.",
    "Develops and attacks e4. Black is not yet worried about the pin.",
    "Castling here is safe because e4 is only loose, not lost.",
    "A modest square, but it unpins and prepares castling.",
    "Backs up e4 so the knight on c6 can be dealt with later.",
    "Gains space and finally shuts the bishop out of the a4-e8 diagonal.",
    "The bishop keeps the good diagonal rather than trading itself off.",
    "Solid. It supports e5 and opens the dark-squared bishop.",
    "The key Ruy move: it builds d4 and gives the bishop c2 to run to.",
    "Black is safe and fully developed. Both sides now manoeuvre.",
  ],
  "Scotch Game": [
    "The most forcing first move at club level.",
    "Symmetry, and a fight for d4 and f4.",
    "Attacks e5 immediately.",
    "The most natural defence.",
    "The Scotch. White opens the centre at once rather than building slowly.",
    "Black must take, or White simply wins the centre outright.",
    "Recaptures with a piece and puts the knight on a strong central square.",
    "Hits the knight and develops. Black plays actively rather than passively.",
    "Defends the knight and prepares to meet the pressure on the diagonal.",
    "Attacks the knight a second time and eyes f2.",
    "Supports the knight and takes b4 and d4 away from Black's pieces.",
    "Develops behind the queen, keeping the bishop's diagonal free.",
  ],
  "Sicilian Najdorf": [
    "White's most ambitious try.",
    "The Sicilian. Black declines symmetry and fights for d4 from the side.",
    "Prepares d4 and develops.",
    "Supports e5 later and opens the c8 bishop. The Najdorf move order.",
    "White strikes in the centre while Black's pieces are still at home.",
    "Black must take, trading a wing pawn for a centre pawn — the Sicilian bargain.",
    "Recaptures and centralises. White has more space; Black has the half-open c-file.",
    "Develops and hits e4, forcing White to attend to the centre.",
    "Defends e4 and develops.",
    "The Najdorf move. It stops Nb5 and Bb5, and prepares b5 and queenside play.",
  ],
  "Caro-Kann, Classical": [
    "The open game.",
    "The Caro-Kann. Modest-looking, but it supports d5 with a pawn rather than a piece.",
    "Builds the big centre.",
    "Now Black hits e4 with full support behind it.",
    "Defends e4 with a piece and develops.",
    "Black resolves the tension and removes White's centre pawn.",
    "Recaptures and centralises the knight.",
    "The whole point of the Caro-Kann: the bishop leaves *before* e6 shuts it in. This is what the French cannot do.",
    "Attacks the bishop and gains time.",
    "The bishop keeps the diagonal and stays safe.",
    "Gains kingside space and threatens to trap the bishop with h5.",
    "Gives the bishop an escape square and stops h5 in its tracks.",
  ],
  "French Defence": [
    "The king's pawn opening.",
    "The French. It prepares d5 with support, at the cost of shutting in the c8 bishop.",
    "Occupies the centre.",
    "The thematic strike. Black challenges e4 at once.",
    "Defends e4 and develops toward the centre.",
    "Attacks e4 a second time and develops.",
    "Pins the knight so the pressure on e4 is only apparent, not real.",
    "Breaks the pin by interposing, and prepares to castle.",
    "White gains space and kicks the knight, gaining time.",
    "Retreating to d7 keeps the knight useful and prepares c5 against the pawn chain.",
  ],
  "Queen's Gambit Declined": [
    "The queen's pawn opening: a slower, more strategic game.",
    "Black claims the centre in kind.",
    "The Queen's Gambit. Not a true gambit — after dxc4 White regains the pawn.",
    "Declining. The pawn holds d5 and Black keeps a solid centre.",
    "Develops and adds a third attacker to d5.",
    "Defends d5 and develops.",
    "Pins the knight and increases the pressure on d5.",
    "Unpins by blocking, and prepares to castle.",
    "Modest, but it opens the f1 bishop and solidifies d4.",
    "King to safety.",
    "Develops the last minor piece and supports the centre.",
    "Asks the bishop a question and gives the king air on the back rank.",
  ],
  "London System": [
    "The queen's pawn opening.",
    "Black takes the centre.",
    "Develops and controls e5.",
    "Develops and controls e4. Both sides are staking out squares.",
    "The London bishop. Get it outside the pawn chain *before* e3, or you bury it.",
    "Develops and prepares to challenge the centre.",
    "Now e3 is right: the bishop is already out, so the pawn shuts in nothing.",
    "Challenges d4 and opens the queen's diagonal.",
    "Supports d4 so the centre holds when Black pushes.",
    "Develops and adds another attacker to d4.",
    "The knight goes to d2, not c3, so the c-pawn keeps supporting d4.",
    "Contests the bishop's diagonal — this is Black's main way to fight the London.",
  ],
  "King's Indian Defence": [
    "The queen's pawn opening.",
    "Black develops and watches the centre from a distance rather than occupying it.",
    "Grabs more space.",
    "Prepares the fianchetto: the bishop will hit the long diagonal.",
    "Develops and supports e4.",
    "The King's Indian bishop. It aims straight through the centre at White's queenside.",
    "White builds the ideal big centre — exactly what Black invited.",
    "Supports e5, the break Black is aiming for.",
    "Defends the centre and prepares to castle.",
    "King to safety, ready for the break.",
    "A modest square, but it keeps everything defended.",
    "The whole point: Black finally strikes at the centre he let White build.",
  ],
  "Nimzo-Indian": [
    "The queen's pawn opening.",
    "Develops and controls e4.",
    "Grabs space and supports d5 ideas.",
    "Prepares d5 and opens the f8 bishop.",
    "Develops and fights for e4 — the square this whole opening is about.",
    "The Nimzo bishop. It pins the knight, so White's grip on e4 is loosened.",
    "Solid. It supports d4 and opens the f1 bishop.",
    "King to safety while the pin does its work.",
    "Develops toward the kingside and supports e4 once more.",
    "Black stakes his own claim in the centre.",
    "Develops and supports d4.",
    "Challenges the centre from the side, the standard Nimzo plan.",
  ],
  "Légal's Mate": [
    "The open game.",
    "Symmetrical reply.",
    "Develops and attacks e5.",
    "Defends.",
    "The Italian bishop, aiming at f7.",
    "Solid, but passive — it shuts in the f8 bishop for now.",
    "Develops and adds pressure to e4 and d5.",
    "Pinning the knight. It looks strong, but the pin is not real — and that is the whole trap.",
    "Asks the bishop a question. Black should probably retreat to d7 or take.",
    "Keeping the pin. Natural, and the losing move.",
    "The point. It looks like White has blundered the queen — the pin was an illusion.",
    "Black takes the queen and loses. Nxe5 first was the way out.",
    "Check, and the king cannot go to a safe square.",
    "Forced.",
    "Mate. Three minor pieces do the work of a queen — the reason to look at pieces, not material.",
  ],
  "Fried Liver Attack": [
    "The open game.",
    "The symmetrical reply.",
    "Attacks e5.",
    "Defends.",
    "Aiming at f7 from the start.",
    "The Two Knights. Active, but it allows what follows.",
    "Attacks f7 twice. Crude, but it must be answered precisely.",
    "The right idea — counterattack rather than defend f7 passively.",
    "Opens the position while Black's king is still in the middle.",
    "Recapturing with the knight walks into the sacrifice. Nb4 or the Traxler avoid it.",
    "The Fried Liver. The knight is given up to drag the king into the open.",
    "Forced — and now the king has no shelter for the rest of the game.",
    "Check, hitting the loose knight on d5 at the same time.",
    "The only move. The king must walk further forward.",
    "Bringing the last piece in. White has two pawns and a raging attack for the piece.",
  ],
  "Englund Gambit Trap": [
    "The queen's pawn opening.",
    "The Englund Gambit. Objectively dubious, but it sets a trap worth knowing from both sides.",
    "Accepting is critical and fine.",
    "Attacks the pawn on e5 and develops.",
    "Defends the pawn. Natural.",
    "Attacks e5 again and eyes the b4 square.",
    "Defends once more, and looks perfectly sensible.",
    "Check, forking the b2 pawn at the same time.",
    "Blocking the check. This is already the wrong idea.",
    "Grabbing the pawn and attacking the rook.",
    "Defends the rook and looks like it holds everything.",
    "Pinning the bishop. Now White has no good answer.",
    "The losing move — and the one the whole gambit is fishing for.",
    "Removing the defender.",
    "Forced recapture.",
    "Mate on the back rank. The queen was never able to leave d2.",
  ],
  "Blackburne Shilling Trap": [
    "The open game.",
    "Symmetry.",
    "Develops with a threat.",
    "Defends.",
    "The Italian bishop.",
    "A provocative move. Black invites Nxe5, which looks like a free pawn.",
    "Taking the bait. Nxd4 is simply good for White instead.",
    "Attacking the knight and g2 at once. Now White is already in trouble.",
    "Grabbing the rook, which loses. Bxf7+ first was the way to survive.",
    "Taking with check on the way to the rook.",
    "Saving the rook, but the king is stuck in the middle.",
    "Check, picking up the pawn and keeping the initiative.",
    "Blocking the check — forced.",
    "Mate. The knight, bishop and queen combine on a king that never castled.",
  ],
};
